version: "3.8"
services:
  proxy:
    build:
      context: .
      dockerfile: ./Dockerfile.proxy
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - redis
    networks:
      main:
        aliases:
          - proxy
  redis:
    image: redis:latest
    command: redis-server --requirepass tLnepVNpNdXk4o9NoEzd4cogN3LoLu4U
    ports:
      - 6379:6379
    networks:
      main:
        aliases:
          - redis
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.server
    depends_on:
      - redis
    command: node --trace-warnings dist/index.js
    networks:
      main:
        aliases:
          - server
    restart: always
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/cerbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      main:
        aliases:
          - certbot
networks:
  main:
